"""users_table added exclude attribute on password field

Revision ID: 996042f8c1fb
Revises: 08c6db4d37e5
Create Date: 2024-10-30 15:22:10.288549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '996042f8c1fb'
down_revision: Union[str, None] = '08c6db4d37e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
